### PR TITLE
Init shared path prefix from a single rank before run

### LINKED ISSUE #1114: `mkpath` on multiple MPI ranks
# Description

When testing Julia 1.4, I came across the following error:
```
ERROR: ERROR: LoadError: LoadError: IOError: mkdir: file already exists (EEXIST)
Stacktrace:IOError: mkdir: file already exists (EEXIST)
Stacktrace:
 [1] uv_error at ./libuv.jl:97 [inlined]
 [2] mkdir(::
 [1] uv_error at ./libuv.jl:97 [inlined]
 [2] String; mode::UInt16) at ./file.jl:177
 [3] mkpath(::String; mode::UInt16) at ./file.jl:227
 [4] mkpath at ./file.jl:222 [inlined]
 [5] mkdir(::run(::MPI.Comm, ::Type{T} where T, ::BrickTopology{2,Float64}, ::SwirlingFlow{Int64}, ::Float64, ::Int64, ::Int64, ::Type{T} where T, ::String, ::Float64) at /central/scratchio/esm/slurmci/sources/bbbe534d902b7508badd82202dac58935e8ea459/tutorials/Numerics/DGmethods/nonnegative.jl:163
 [6] top-level scope at /central/scratchio/esm/slurmci/sources/bbbe534d902b7508badd82202dac58935e8ea459/tutorials/Numerics/DGmethods/nonnegative.jl:247
 [7] include(::Module, ::String) at ./Base.jl:377
 [8] exec_options(::Base.JLOptions) at ./client.jl:288
 [9] _start() at ./client.jl:484
in expression starting at /central/scratchio/esm/slurmci/sources/bbbe534d902b7508badd82202dac58935e8ea459/tutorials/Numerics/DGmethods/nonnegative.jl:202
String; mode::UInt16) at ./file.jl:177
 [3] mkpath(::String; mode::UInt16) at ./file.jl:227
 [4] mkpath at ./file.jl:222 [inlined]
 [5] run(::MPI.Comm, ::Type{T} where T, ::BrickTopology{2,Float64}, ::SwirlingFlow{Int64}, ::Float64, ::Int64, ::Int64, ::Type{T} where T, ::String, ::Float64) at /central/scratchio/esm/slurmci/sources/bbbe534d902b7508badd82202dac58935e8ea459/tutorials/Numerics/DGmethods/nonnegative.jl:163
 [6] top-level scope at /central/scratchio/esm/slurmci/sources/bbbe534d902b7508badd82202dac58935e8ea459/tutorials/Numerics/DGmethods/nonnegative.jl:247
 [7] include(::Module, ::String) at ./Base.jl:377
 [8] exec_options(::Base.JLOptions) at ./client.jl:288
 [9] _start() at ./client.jl:484
```

https://gist.github.com/climabot/767c3b19502d5e096969154a211ebc59#file-out_9882097

I'm not exactly sure what is going on here, but it could be that we are hitting a race condition when `mkpath` is called on multiple MPI ranks.

For now the simplest option is to only call `mkdir` on rank 0 + `MPI.Barrier`, but we should look into what https://github.com/hpc/mpifileutils/ does.

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

### PR DESCRIPTION
**Pull request by jakebolewski**
# Description
Only create top-level prefix path on rank 0 of a communicator group to prevent output race conditions.  This doesn't impact unit tests because they are run sequentially, but slurm-ci tests have issues if multiple concurrent tests are scheduled to write to a common prefix.  We'll need to also change slurm-ci so that jobs don't write to a common prefix for test output.

Closes #1114 

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [x] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

File: src/Driver/Driver.jl [hunk 1]
```diff
@@ -253,13 +253,16 @@ function init(; disable_gpu = false, arg_settings = nothing)
...
 
-    # create the output directory if needed
-    if Settings.diagnostics !== "never" || Settings.vtk !== "never"
-        mkpath(Settings.output_dir)
-    end
-    if Settings.checkpoint !== "never" || Settings.checkpoint_at_end
-        mkpath(Settings.checkpoint_dir)
+    # create the output directory if needed on delegated rank
+    if MPI.Comm_rank(MPI.COMM_WORLD) == 0
+        if Settings.diagnostics !== "never" || Settings.vtk !== "never"
```
Comment (simonbyrne) [inline src/Driver/Driver.jl:258]: These probably shouldn't be testing for identity:
```suggestion
        if Settings.diagnostics != "never" || Settings.vtk != "never"
```

File: src/Driver/Driver.jl [hunk 2]
```diff
@@ -253,13 +253,16 @@ function init(; disable_gpu = false, arg_settings = nothing)
...
+            mkpath(Settings.output_dir)
+        end
+        if Settings.checkpoint !== "never" || Settings.checkpoint_at_end
```
Comment (simonbyrne) [inline src/Driver/Driver.jl:261]:
```suggestion
        if Settings.checkpoint != "never" || Settings.checkpoint_at_end
```

File: tutorials/Microphysics/ex_1_saturation_adjustment.jl [hunk 3]
```diff
@@ -210,19 +210,27 @@ function main()
     mpicomm = MPI.COMM_WORLD
 
     # output for paraview
+
+    # initialize base prefix directory from rank 0
+    vtkdir = abspath(joinpath(ClimateMachine.Settings.output_dir, "vtk"))
```
Comment (simonbyrne) [inline tutorials/Microphysics/ex_1_saturation_adjustment.jl:215]: do we need to check if `Settings.vtk != "never"`? Otherwise what will happen if no argument is used?

Comment (jakebolewski) [reply tutorials/Microphysics/ex_1_saturation_adjustment.jl:215]: what should be the behaviour to be in that case?  error out if the output directory is not defined?

Comment (jakebolewski) [reply tutorials/Microphysics/ex_1_saturation_adjustment.jl:215]: maybe run the simulation but skip over output generation?

Comment (simonbyrne) [reply tutorials/Microphysics/ex_1_saturation_adjustment.jl:215]: ah, i was worried that the output directory wasn't defined by default. I think this looks fine.

**Comment by simonbyrne** [comment]
this doesn't fix the issue of multiple jobs writing to the same place. The easiest option for now would be to add `--output-dir=<unique job name>` in slurmci-test.toml

**Comment by jakebolewski** [comment]
Yes this needs something on the slurmci side as well.  In general writing to relative directories on multiple nodes / ranks is not really well defined.  Probably there needs to be some way of overloading the base prefix, which is relative to `--output-dir` and enforcing at setup that the base path prefix is absolute.

**Comment by jakebolewski** [comment]
There seems to only be a handful of tests that do output, and they all run on a single node, so Ill add the relative path construction suggested above for now.

**Comment by charleskawczynski** [comment]
Should we be dumping this much data to disk in the tutorials? I ended up removing `write_data` calls altogether in the heat equation tutorial. The experiments are probably a different story, though.

**Comment by jakebolewski** [comment]
@charleskawczynski I would think not, probably "tests" that generate output that is not checked by a computer are better run periodically

File: slurmci-test.toml [hunk 4]
```diff
@@ -38,7 +38,7 @@ cpu_gpu = [
   { file = "test/Numerics/LinearSolvers/bandedsystem.jl", slurmargs = ["--ntasks=3", "--time=02:00:00"], args = [] },
   { file = "test/Numerics/Mesh/interpolation.jl", slurmargs = ["--ntasks=3", "--time=02:00:00"], args = [] },
   { file = "test/Ocean/ShallowWater/GyreDriver.jl", slurmargs = ["--ntasks=1"], args = [] },
-  { file = "tutorials/Numerics/DGmethods/nonnegative.jl", slurmargs = ["--ntasks=3"], args = [] },
+  { file = "tutorials/Numerics/DGmethods/nonnegative.jl", slurmargs = ["--ntasks=3"], args = ["--output-dir=output/dgmethods_nonnegative"] },
```
Comment (simonbyrne) [inline slurmci-test.toml:41]: This might have to be moved to have separate ones on gpu and cpu, since otherwise both jobs will use the same directory.

**Comment by simonbyrne** [comment]
I think you're right about the environment variable being the simplest option. Ideally we would make the default value of `output-dir` be overrideable by an environment variable (e.g. `CLIMATEMACHINE_OUTPUT_DIR`, so we could set it in the slurm script. I'm not sure if this is supported by the ArgParse package.

**Comment by simonbyrne** [comment]
I'm trying this out with https://github.com/CliMA/slurmci/pull/35

File: tutorials/Microphysics/ex_2_Kessler.jl [hunk 5]
```diff
@@ -350,18 +350,25 @@ function main()
         end
 
     # output for paraview
+
+    # initialize base output prefix directory from rank 0
```
Comment (simonbyrne) [inline tutorials/Microphysics/ex_2_Kessler.jl:354]:
```suggestion
    # initialize base prefix directory from rank 0
    vtkdir = abspath(joinpath(ClimateMachine.Settings.output_dir, "vtk"))
```

File: tutorials/Numerics/DGmethods/nonnegative.jl [hunk 6]
```diff
@@ -229,7 +234,10 @@ let
     CFL = 1
     dt = CFL * dx / maxvelocity
 
-    vtkdir = "vtk_nonnegative"
+    vtkdir = abspath(joinpath(
+        ClimateMachine.Settings.output_path,
```
Comment (simonbyrne) [inline tutorials/Numerics/DGmethods/nonnegative.jl:238]:
```suggestion
        ClimateMachine.Settings.output_dir,
```
