### PR TITLE
Validate `ClimateMachine.init()` keyword arguments

### LINKED ISSUE #1333: ClimateMachine.init() doesn't error if you misspell an optional argument
# Description

If you type `ClimateMachine.init(dsisable_gpu = true)`, the file will execute perfectly fine on the GPU without raising an error.  I imagine similar things happen for the other named arguments. It would be nice if it raised a warning or error instead of silently executing with the default options.

## Steps to reproduce

Make a typo in any named argument when using ClimateMachine.init().

## Expected behavior

Tell me that I passed a non-existent named argument.

## Additional context

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

### PR DESCRIPTION
**Pull request by kpamnany**
# Description

Closes #1333.

I have

- [X] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [X] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [X] There are no open pull requests for this already
- [X] CLIMA developers with relevant expertise have been assigned to review this submission
- [X] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [X] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

File: src/Driver/Driver.jl [hunk 1]
```diff
@@ -340,10 +335,24 @@ function init(;
...
+    # `Settings` contains global defaults
+    global_defaults = Dict{Symbol, Any}(
+        (n, getproperty(Settings, n)) for n in propertynames(Settings)
+    )
+
+    # keyword arguments must be applicable to `Settings`
     all_args = Dict{Symbol, Any}(keyword_args)
+    for kwarg in keys(all_args)
+        if get(global_defaults, kwarg, nothing) === nothing
+            @warn("Unrecognized keyword argument '$(string(kwarg))'; ignoring")
```
Comment (blallen) [inline src/Driver/Driver.jl:347]: Are there any disadvantages to making this return an error instead of a warning?

Comment (leios) [inline src/Driver/Driver.jl:347]: Maybe it's a good idea to error instead of warn? I don't really have a preference either way, but if users configure their simulation and get results when they actually wanted a different sim, that could be a problem.

Comment (blallen) [reply src/Driver/Driver.jl:347]: Are there any disadvantages to making this return an error instead of a warning?

Comment (jakebolewski) [reply src/Driver/Driver.jl:347]: I think an error would be better as well.  For custom CI arguments you can pass in the defaults with the argparse settings so I don't see a need to not strictly validate the arguments

Comment (kpamnany) [reply src/Driver/Driver.jl]: I'm now making it throw an `ArgumentError` but am happy to do something else if anyone has a suggestion.
